openapi: 3.0.2
info:
  contact:
    email: rlee@163.com
    name: Ryan Li
  license:
    name: MIT
    url: https://mit-license.org/
  title: 上报审批系统后台服务 API
  version: 0.9.0
servers:
  - url: http://localhost:3000/rest
  - url: http://{host}:{port}/{contextPath}
    variables:
      host:
        default: localhost
      port:
        default: "9003"
      contextPath:
        default: rest
paths:
  /application/create:
    post:
      description: 申请人在“申请页面”填写相关信息并提交申请，将调用此 API 来创建一个新申请。
      operationId: createApplication
      requestBody:
        content:
          application/json:
            examples:
              包干修复初审:
                value:
                  state: 初审
                  type: 包干修复
                  applicant: 定损员A
                  startDate: 2020-06-30T14:10:20.391
                  caseNo: PICC-123456
                  plateNo: 鄂A-12345
                  vehicleModel: 奔驰 GLC 260 豪华型
                  repairPlant: 武汉星隆汽车销售服务有限公司
                  actualCost: "250000"
                  evaluationCost: "250000"
                  purchasePrice: "422800"
                  agreementAmount: "100000"
                  investigator: 定损员A
                  investigateDate: 2020-06-28
              高价值件初审:
                value:
                  state: 初审
                  type: 高价值件
                  applicant: 定损员A
                  startDate: 2020-06-30T14:10:20.391
                  caseNo: PICC-123456
                  plateNo: 鄂A-12345
                  vehicleModel: 奔驰 GLC 260 豪华型
                  investigator: 定损员A
                  investigateLocation: 武汉星隆汽车销售服务有限公司
                  investigateDate: 2020-06-28
                  identifier: LBVNPU39008SB69093
                  insurer: 市人保营业部
                  insured: 奔驰车主
                  finalAmount: "50000"
                  deductible: "10000"
              总成部件初审:
                value:
                  state: 初审
                  type: 总成部件
                  applicant: 定损员A
                  startDate: 2020-06-30T14:10:20.391
                  caseNo: PICC-123456
                  plateNo: 鄂A-12345
                  vehicleModel: 奔驰 GLC 260 豪华型
                  investigator: 定损员A
                  investigateLocation: 武汉星隆汽车销售服务有限公司
                  investigateDate: 2020-06-28
                  identifier: LBVNPU39008SB69093
                  insurer: 市人保营业部
                  insured: 奔驰车主
                  finalAmount: "100000"
                  deductible: "20000"
              调价申请初审:
                value:
                  state: 初审
                  type: 包干修复
                  applicant: 定损员A
                  startDate: 2020-06-30T14:10:20.391
                  caseNo: PICC-123456
                  plateNo: 鄂A-12345
                  vehicleModel: 奔驰 GLC 260 豪华型
                  investigator: 定损员A
                  investigateDate: 2020-06-28
                  occurredDate: 2020-06-14
                  quoteDate: 2020-06-25
                  quoteAmount: "20000"
                  targetAmount: "25000"
            schema:
              $ref: "#/components/schemas/ApplicationDetailsDto"
        required: true
      responses:
        "200":
          content:
            application/json:
              example:
                code: 20000
                data:
                  id: bc8d2f78-ba94-11ea-b3de-0242ac130004
              schema:
                $ref: "#/components/schemas/ApplicationCreateResDto"
          description: OK
      summary: 创建一个申请
      tags:
        - Application
      x-eov-operation-handler: controllers/ApplicationController
  /task:
    post:
      description: 通过用户名和用户角色来查询相关的用户任务
      operationId: getTaskList
      requestBody:
        content:
          application/json:
            example:
              username: 张三
              roles:
                - 组长
                - 包干修复初审
            schema:
              $ref: "#/components/schemas/TaskQueryDto"
        required: true
      responses:
        "200":
          description: OK
      summary: 查询用户任务
      tags:
        - Task
      x-eov-operation-handler: controllers/TaskController
components:
  schemas:
    ResponseCode:
      properties:
        code:
          description: |
            `20000`: 操作成功 <br> `60204`: 不正确的用户名或密码 <br> `50008`: 无效的 token <br> `50012`: 已在其它客户端登录 <br> `50014`: 过期的 token
          type: integer
      type: object
    ApplicationDetailsDto:
      example:
        identifier: identifier
        agreementAmount: agreementAmount
        insured: insured
        plateNo: plateNo
        targetAmount: targetAmount
        purchasePrice: purchasePrice
        type: 包干修复
        caseNo: caseNo
        applicant: applicant
        quotedAmount: quotedAmount
        investigator: investigator
        offerDate: offerDate
        insurer: insurer
        finalAmount: finalAmount
        evaluationCost: evaluationCost
        deductible: deductible
        vehicleModel: vehicleModel
        repairPlant: repairPlant
        state: 初审
        startDate: startDate
        investigateLocation: investigateLocation
        actualCost: actualCost
        investigateDate: investigateDate
        occurredDate: occurredDate
      properties:
        state:
          description: 审批状态。开始申请时，状态为“初审”。
          enum:
            - 初审
            - 复审
          type: string
        type:
          description: 审批类型。
          enum:
            - 包干修复
            - 高价值件
            - 总成部件
            - 调价申请
          type: string
        applicant:
          description: 申请人用户名（username）。
          type: string
        startDate:
          description: 提交申请的时间，格式为`ISO8601_FORMAT`。
          type: string
        caseNo:
          description: 报案号
          type: string
        plateNo:
          description: 车牌号
          type: string
        vehicleModel:
          description: 车辆型号
          type: string
        repairPlant:
          description: 修理厂名称
          type: string
        actualCost:
          description: 实际价值
          type: string
        evaluationCost:
          description: 评估价值
          type: string
        purchasePrice:
          description: 新车购置价
          type: string
        agreementAmount:
          description: 一次性协议定损金额
          type: string
        investigator:
          description: 定损员真实姓名（name）。
          type: string
        investigateLocation:
          description: 定损地点
          type: string
        investigateDate:
          description: 定损时间
          type: string
        identifier:
          description: 识别代码
          type: string
        insurer:
          description: 承保公司
          type: string
        insured:
          description: 被保险人姓名
          type: string
        finalAmount:
          description: 最终价格
          type: string
        deductible:
          description: 自付标准
          type: string
        occurredDate:
          description: 出险时间
          type: string
        offerDate:
          description: 报价时间
          type: string
        quotedAmount:
          description: 报价金额
          type: string
        targetAmount:
          description: 目标金额
          type: string
      required:
        - applicant
        - startDate
        - state
        - type
      type: object
    ApplicationCreateResDto:
      allOf:
        - $ref: "#/components/schemas/ResponseCode"
        - $ref: "#/components/schemas/ApplicationCreateResDto_allOf"
    TaskQueryDto:
      example:
        roles:
          - roles
          - roles
        username: username
      properties:
        username:
          description: 用户名
          type: string
        roles:
          description: 用户角色
          items:
            type: string
          type: array
      type: object
    TaskQueryResDto:
      allOf:
        - $ref: "#/components/schemas/ResponseCode"
        - $ref: "#/components/schemas/TaskQueryResDto_allOf"
    ApplicationCreateResDto_allOf_data:
      properties:
        id:
          description: Application id
          type: string
    ApplicationCreateResDto_allOf:
      properties:
        data:
          $ref: "#/components/schemas/ApplicationCreateResDto_allOf_data"
    TaskQueryResDto_allOf:
      properties:
        data:
          items:
            $ref: "#/components/schemas/ApplicationDetailsDto"
          type: array
