openapi: 3.0.0
info:
  version: 0.1.0
  title: 上报审批系统 API
  description: 上报审批系统前后台交互 API 定义
  contact:
    name: Ryan Li
    email: rlee@163.com
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
servers:
  - url: /api
paths:
  /users/login:
    post:
      summary: 用户登录
      operationId: login
      tags:
        - users
        
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
              example:
                username: 'dingsun'
                password: '123'
      
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: >
                      `20000`: 登录成功 <br>
                      `60204`: 不正确的用户名或密码
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                  message:
                    type: string
              examples:
                登录成功:
                  value:
                    code: '20000'
                    data: 
                      token: 'dingsun-token'
                登录失败:
                  value:
                    code: '60204'
                    message: '不正确的用户名或密码'
        default:
          description: 未知错误
          
  /users/info:
    get:
      summary: 获取用户信息
      description: >
        通过 token 获取用户信息，必须先登录成功。
      operationId: getInfo
      tags: 
        - users
        
      parameters: 
        - name: token
          description: 用户 token
          in: query
          required: true
          schema:
            type: string
            example: 'dingsun-token'
            
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: >
                      `20000`: 获取成功 <br>
                      `50008`: 无效的 token <br>
                      `50012`: 已在其它客户端登录 <br>
                      `50014`: 过期的 token
                  data: 
                    type: object
                    properties:
                      name:
                        type: string
                        description: 用户的真实姓名
                      avatar:
                        type: string
                        description: 用户头像的 url
                example:
                  code: '20000'
                  data:
                    name: '定损员'
                    avatar: '/avatar/memberOfLosses.png'
        default:
          description: 未知错误
                    
  /users/logout:
    post:
      summary: 用户登出
      operationId: logout
      tags: 
        - users
        
      parameters: 
        - in: header
          name: X-Token
          description: 通过 `header` 中的 `X-Token` 来传递 token
          required: true
          schema:
            type: string
            example: 'dingsun-token'
      
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  data:
                    type: string
                example: 
                  code: '200'
                  data: 'success'
        default:
          description: 未知错误
