/**
 * 审批流程 API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5.0
 * Contact: rlee@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApprovalDetails from './ApprovalDetails';

/**
* The ApprovalHistory model module.
* @module model/ApprovalHistory
* @version 0.5.0
*/
export default class ApprovalHistory {
    /**
    * Constructs a new <code>ApprovalHistory</code>.
    * @alias module:model/ApprovalHistory
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ApprovalHistory</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ApprovalHistory} obj Optional instance to populate.
    * @return {module:model/ApprovalHistory} The populated <code>ApprovalHistory</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApprovalHistory();
                        
            
            if (data.hasOwnProperty('approvalHistory')) {
                obj['approvalHistory'] = ApiClient.convertToType(data['approvalHistory'], [ApprovalDetails]);
            }
        }
        return obj;
    }

    /**
    * 审核历史记录，按时间倒序排列。
    * @member {Array.<module:model/ApprovalDetails>} approvalHistory
    */
    'approvalHistory' = undefined;




}
