/**
 * 审批流程 API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5.0
 * Contact: rlee@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApplicationDetails from './ApplicationDetails';
import ApprovalDetails from './ApprovalDetails';
import ApprovalHistory from './ApprovalHistory';

/**
* The InlineResponse2002 model module.
* @module model/InlineResponse2002
* @version 0.5.0
*/
export default class InlineResponse2002 {
    /**
    * Constructs a new <code>InlineResponse2002</code>.
    * @alias module:model/InlineResponse2002
    * @class
    * @extends module:model/ApplicationDetails
    * @param state {} 审批状态。开始申请时，状态为“初审”。
    * @param type {} 审批类型。
    * @param applicant {} 申请人，也就是定损员。
    * @param startDate {} 提交申请的时间。
    */

    constructor(state, type, applicant, startDate) {
        ApplicationDetails.call(this, state, type, applicant, startDate);
        
        
    }

    /**
    * Constructs a <code>InlineResponse2002</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse2002} obj Optional instance to populate.
    * @return {module:model/InlineResponse2002} The populated <code>InlineResponse2002</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2002();
            
            ApplicationDetails.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('approvalHistory')) {
                obj['approvalHistory'] = ApiClient.convertToType(data['approvalHistory'], [ApprovalDetails]);
            }
        }
        return obj;
    }

    /**
    * 审核历史记录，按时间倒序排列。
    * @member {Array.<module:model/ApprovalDetails>} approvalHistory
    */
    'approvalHistory' = undefined;




}
