apps:
  - name: "ums-service"
    script: "index.js"
    cwd: "/src"
    watch: true
    ignore_watch:
      - "node_modules"
      - "*.log"
    watch_options:
      usePolling: true
      interval: 1000
