#!/bin/bash

CAMUNDA_COMPOSE_FILE="$PWD/camunda/docker-compose.yaml"
UMS_COMPOSE_FILE="$PWD/ums/docker-compose.yaml"

docker-compose -f $CAMUNDA_COMPOSE_FILE up -d
docker-compose -f $UMS_COMPOSE_FILE up -d