/**
 * 审批流程 API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5.0
 * Contact: rlee@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ApplicationDetails model module.
* @module model/ApplicationDetails
* @version 0.5.0
*/
export default class ApplicationDetails {
    /**
    * Constructs a new <code>ApplicationDetails</code>.
    * @alias module:model/ApplicationDetails
    * @class
    * @param state {module:model/ApplicationDetails.StateEnum} 审批状态。开始申请时，状态为“初审”。
    * @param type {module:model/ApplicationDetails.TypeEnum} 审批类型。
    * @param applicant {String} 申请人，也就是定损员。
    * @param startDate {String} 提交申请的时间。
    */

    constructor(state, type, applicant, startDate) {
        
        
        this['state'] = state;
        this['type'] = type;
        this['applicant'] = applicant;
        this['startDate'] = startDate;
        
    }

    /**
    * Constructs a <code>ApplicationDetails</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ApplicationDetails} obj Optional instance to populate.
    * @return {module:model/ApplicationDetails} The populated <code>ApplicationDetails</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationDetails();
                        
            
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('applicant')) {
                obj['applicant'] = ApiClient.convertToType(data['applicant'], 'String');
            }
            if (data.hasOwnProperty('startDate')) {
                obj['startDate'] = ApiClient.convertToType(data['startDate'], 'String');
            }
            if (data.hasOwnProperty('reportNo')) {
                obj['reportNo'] = ApiClient.convertToType(data['reportNo'], 'String');
            }
            if (data.hasOwnProperty('plateNo')) {
                obj['plateNo'] = ApiClient.convertToType(data['plateNo'], 'String');
            }
            if (data.hasOwnProperty('vehicleModel')) {
                obj['vehicleModel'] = ApiClient.convertToType(data['vehicleModel'], 'String');
            }
            if (data.hasOwnProperty('repairPlant')) {
                obj['repairPlant'] = ApiClient.convertToType(data['repairPlant'], 'String');
            }
            if (data.hasOwnProperty('actualCost')) {
                obj['actualCost'] = ApiClient.convertToType(data['actualCost'], 'String');
            }
            if (data.hasOwnProperty('evaluationCost')) {
                obj['evaluationCost'] = ApiClient.convertToType(data['evaluationCost'], 'String');
            }
            if (data.hasOwnProperty('purchasePrice')) {
                obj['purchasePrice'] = ApiClient.convertToType(data['purchasePrice'], 'String');
            }
            if (data.hasOwnProperty('agreementAmount')) {
                obj['agreementAmount'] = ApiClient.convertToType(data['agreementAmount'], 'String');
            }
            if (data.hasOwnProperty('investigator')) {
                obj['investigator'] = ApiClient.convertToType(data['investigator'], 'String');
            }
            if (data.hasOwnProperty('investigateLocation')) {
                obj['investigateLocation'] = ApiClient.convertToType(data['investigateLocation'], 'String');
            }
            if (data.hasOwnProperty('investigateDate')) {
                obj['investigateDate'] = ApiClient.convertToType(data['investigateDate'], 'String');
            }
            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('insurer')) {
                obj['insurer'] = ApiClient.convertToType(data['insurer'], 'String');
            }
            if (data.hasOwnProperty('insured')) {
                obj['insured'] = ApiClient.convertToType(data['insured'], 'String');
            }
            if (data.hasOwnProperty('finalAmount')) {
                obj['finalAmount'] = ApiClient.convertToType(data['finalAmount'], 'String');
            }
            if (data.hasOwnProperty('deductible')) {
                obj['deductible'] = ApiClient.convertToType(data['deductible'], 'String');
            }
            if (data.hasOwnProperty('occurredDate')) {
                obj['occurredDate'] = ApiClient.convertToType(data['occurredDate'], 'String');
            }
            if (data.hasOwnProperty('quoteDate')) {
                obj['quoteDate'] = ApiClient.convertToType(data['quoteDate'], 'String');
            }
            if (data.hasOwnProperty('quoteAmount')) {
                obj['quoteAmount'] = ApiClient.convertToType(data['quoteAmount'], 'String');
            }
            if (data.hasOwnProperty('targetAmount')) {
                obj['targetAmount'] = ApiClient.convertToType(data['targetAmount'], 'String');
            }
        }
        return obj;
    }

    /**
    * 审批状态。开始申请时，状态为“初审”。
    * @member {module:model/ApplicationDetails.StateEnum} state
    */
    'state' = undefined;
    /**
    * 审批类型。
    * @member {module:model/ApplicationDetails.TypeEnum} type
    */
    'type' = undefined;
    /**
    * 申请人，也就是定损员。
    * @member {String} applicant
    */
    'applicant' = undefined;
    /**
    * 提交申请的时间。
    * @member {String} startDate
    */
    'startDate' = undefined;
    /**
    * 报案号
    * @member {String} reportNo
    */
    'reportNo' = undefined;
    /**
    * 车牌号
    * @member {String} plateNo
    */
    'plateNo' = undefined;
    /**
    * 车辆型号
    * @member {String} vehicleModel
    */
    'vehicleModel' = undefined;
    /**
    * 修理厂名称
    * @member {String} repairPlant
    */
    'repairPlant' = undefined;
    /**
    * 实际价值
    * @member {String} actualCost
    */
    'actualCost' = undefined;
    /**
    * 评估价值
    * @member {String} evaluationCost
    */
    'evaluationCost' = undefined;
    /**
    * 新车购置价
    * @member {String} purchasePrice
    */
    'purchasePrice' = undefined;
    /**
    * 一次性协议定损金额
    * @member {String} agreementAmount
    */
    'agreementAmount' = undefined;
    /**
    * 定损员
    * @member {String} investigator
    */
    'investigator' = undefined;
    /**
    * 定损地点
    * @member {String} investigateLocation
    */
    'investigateLocation' = undefined;
    /**
    * 定损时间
    * @member {String} investigateDate
    */
    'investigateDate' = undefined;
    /**
    * 识别代码
    * @member {String} identifier
    */
    'identifier' = undefined;
    /**
    * 承保公司
    * @member {String} insurer
    */
    'insurer' = undefined;
    /**
    * 被保险人姓名
    * @member {String} insured
    */
    'insured' = undefined;
    /**
    * 最终价格
    * @member {String} finalAmount
    */
    'finalAmount' = undefined;
    /**
    * 自付标准
    * @member {String} deductible
    */
    'deductible' = undefined;
    /**
    * 出险时间
    * @member {String} occurredDate
    */
    'occurredDate' = undefined;
    /**
    * 报价时间
    * @member {String} quoteDate
    */
    'quoteDate' = undefined;
    /**
    * 报价金额
    * @member {String} quoteAmount
    */
    'quoteAmount' = undefined;
    /**
    * 目标金额
    * @member {String} targetAmount
    */
    'targetAmount' = undefined;



    /**
    * Allowed values for the <code>state</code> property.
    * @enum {String}
    * @readonly
    */
    static StateEnum = {
        /**
         * value: "初审"
         * @const
         */
        "初审": "初审",
        /**
         * value: "复审"
         * @const
         */
        "复审": "复审"    };
    /**
    * Allowed values for the <code>type</code> property.
    * @enum {String}
    * @readonly
    */
    static TypeEnum = {
        /**
         * value: "包干修复"
         * @const
         */
        "包干修复": "包干修复",
        /**
         * value: "高价值件"
         * @const
         */
        "高价值件": "高价值件",
        /**
         * value: "总成部件"
         * @const
         */
        "总成部件": "总成部件",
        /**
         * value: "调价申请"
         * @const
         */
        "调价申请": "调价申请"    };

}
