/**
 * 审批流程 API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5.0
 * Contact: rlee@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ApprovalDetails model module.
* @module model/ApprovalDetails
* @version 0.5.0
*/
export default class ApprovalDetails {
    /**
    * Constructs a new <code>ApprovalDetails</code>.
    * @alias module:model/ApprovalDetails
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ApprovalDetails</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ApprovalDetails} obj Optional instance to populate.
    * @return {module:model/ApprovalDetails} The populated <code>ApprovalDetails</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApprovalDetails();
                        
            
            if (data.hasOwnProperty('approver')) {
                obj['approver'] = ApiClient.convertToType(data['approver'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('approved')) {
                obj['approved'] = ApiClient.convertToType(data['approved'], 'Boolean');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
        }
        return obj;
    }

    /**
    * 审核人
    * @member {String} approver
    */
    'approver' = undefined;
    /**
    * 审核时间
    * @member {String} date
    */
    'date' = undefined;
    /**
    * 审核结果。true：通过；false：不通过
    * @member {Boolean} approved
    */
    'approved' = undefined;
    /**
    * 审核意见
    * @member {String} comment
    */
    'comment' = undefined;




}
