/**
 * 审批流程 API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5.0
 * Contact: rlee@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TaskQuery model module.
* @module model/TaskQuery
* @version 0.5.0
*/
export default class TaskQuery {
    /**
    * Constructs a new <code>TaskQuery</code>.
    * @alias module:model/TaskQuery
    * @class
    * @param userId {String} 用户 id
    */

    constructor(userId) {
        
        
        this['userId'] = userId;
        
    }

    /**
    * Constructs a <code>TaskQuery</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TaskQuery} obj Optional instance to populate.
    * @return {module:model/TaskQuery} The populated <code>TaskQuery</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaskQuery();
                        
            
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('reportNo')) {
                obj['reportNo'] = ApiClient.convertToType(data['reportNo'], 'String');
            }
            if (data.hasOwnProperty('plateNo')) {
                obj['plateNo'] = ApiClient.convertToType(data['plateNo'], 'String');
            }
        }
        return obj;
    }

    /**
    * 用户 id
    * @member {String} userId
    */
    'userId' = undefined;
    /**
    * 申请类型
    * @member {module:model/TaskQuery.TypeEnum} type
    */
    'type' = undefined;
    /**
    * 报案号
    * @member {String} reportNo
    */
    'reportNo' = undefined;
    /**
    * 车牌号
    * @member {String} plateNo
    */
    'plateNo' = undefined;



    /**
    * Allowed values for the <code>type</code> property.
    * @enum {String}
    * @readonly
    */
    static TypeEnum = {
        /**
         * value: "包干修复"
         * @const
         */
        "包干修复": "包干修复",
        /**
         * value: "高价值件"
         * @const
         */
        "高价值件": "高价值件",
        /**
         * value: "总成部件"
         * @const
         */
        "总成部件": "总成部件",
        /**
         * value: "调价申请"
         * @const
         */
        "调价申请": "调价申请"    };

}
