openapi: 3.0.0

info:
  version: 0.1.0
  title: 上报审批系统 API
  description: 上报审批系统前后台交互 API 定义
  contact:
    name: Ryan Li
    email: rlee@163.com

servers:
  - url: /api

paths:
  /users/login:
    post:
      summary: 用户登录
      operationId: login
      tags:
        - users
        
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
              example:
                username: "dingsun"
                password: "123"
      
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int64
                    description: >
                      `20000`: 登录成功 <br>
                      `60204`: 不正确的用户名或密码
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                  message:
                    type: string
              examples:
                登录成功:
                  value:
                    code: 20000
                    data: 
                      token: dingsun-token
                登录失败:
                  value:
                    code: 60204
                    message: "不正确的用户名或密码"
        default:
          description: 未知错误
          
  /users/info:
    get:
      summary: 获取用户信息
      description: >
        通过 token 获取用户信息，必须先登录成功。
      operationId: getInfo
      tags: 
        - users
        
      parameters: 
        - name: token
          description: 用户 token
          in: query
          required: true
          schema:
            type: string
            example: 'dingsun-token'
            
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int64
                    description: >
                      `20000`: 获取成功 <br>
                      `50008`: 无效的 token <br>
                      `50012`: 已在其它客户端登录 <br>
                      `50014`: 过期的 token
                  data: 
                    type: object
                    properties:
                      name:
                        type: string
                        description: 用户的真实姓名
                      avatar:
                        type: string
                        description: 用户头像的 url
                      introduction:
                        type: string
                        description: 用户的详细介绍
                      roles:
                        type: array
                        items:
                          type: string
                          description: 用户所属的角色列表

                example:
                  code: 20000
                  data:
                    name: '定损员'
                    avatar: '/avatar/memberOfLosses.png'
                    introduction: '定损员可以创建申请'
                    roles: [ '定损员' ]
        default:
          description: 未知错误
                    
  /users/logout:
    post:
      summary: 用户登出
      operationId: logout
      tags: 
        - users
        
      parameters: 
        - in: header
          name: X-Token
          description: 通过 `header` 中的 `X-Token` 来传递 token
          required: true
          schema:
            type: string
            example: 'dingsun-token'
      
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int64
                  data:
                    type: string
                example: 
                  code: 20000
                  data: 'success'
        default:
          description: 未知错误

  /tasks/submitApplication:
    post:
      summary: 提交申请
      operationId: submitApplication
      tags:
        - tasks

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  description: >
                    申请类别："包干修复"、"高价值件"、"总成部件"、"调价"
                startUsername:
                  type: string
                  description: 发起申请的用户名
                details:
                  type: object
              required:
                - type
                - startUsername
              example:
                type: "包干修复"
                startUsername: "dingsun"
                details:
                  报案号: "RDAA202032010000001395"
                  车牌号: "鄂A-12345"
                  车辆型号: "大众途观"
                  修理厂名称: "大众"
                  实际价值: 50000
                  评估底价: 50000
                  新车购置价: 200000
                  一次性协议定损金额: 50000
                  照片列表:
                    - "/upload-image/1.jpg"
                    - "/upload-image/2.jpg"
                  定损员: "dingsun"
                  定损时间: "2020-06-16"
      
      responses:
        '200': 
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: 任务 id，全局唯一，用于访问流程的所有信息。
                example:
                  id: "37bcdd0a-af7e-11ea-b3de-0242ac130004"

  /tasks/queryApplication:
    post:
      summary: 查询申请列表及详情
      operationId: queryApplication
      tags:
        - tasks

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                startUsername:
                  type: string
                  description: 申请的发起人用户名
                currentUsername:
                  type: string
                  description: 流程查询人用户名。**必填**，只能查询与该用户相关的流程。
              required:
                - currentUsername
              example:
                currentUsername: "leader"

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      type: object
                      properties:
                        id: 
                          type: string
                          description: 任务 id，全局唯一，用于访问流程的所有信息。
                example:
                  tasks:
                    - id: "37bcdd0a-af7e-11ea-b3de-0242ac130004"
                    - id: "f68a9490-af81-11ea-b3de-0242ac130004"
                