version: "3.8"

services:
  ums-service:
    build:
      context: build

    image: keymetrics/pm2:latest-stretch
    container_name: ums-service
    ports:
      - 9002:3000

  openldap:
    image: osixia/openldap:latest
    container_name: ums-openldap
    environment:
      - LDAP_ORGANISATION=User Managment System # 组织的名字
      - LDAP_DOMAIN=ums # 公司域名，用于 BASE_DN，不可修改，否则数据库无法启动
      - LDAP_ADMIN_PASSWORD=root # 管理员密码
    volumes:
      - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom # 加载测试数据
      - openldap-db:/var/lib/ldap
      - openldap-config:/etc/ldap/slapd.d
    expose:
      - 389
    command: --copy-service

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ums-phpldapadmin
    environment:
      - PHPLDAPADMIN_HTTPS=false # 关闭HTTPS，开启HTTP。（HTTPS和HTTP只能开启一个）
      - PHPLDAPADMIN_LDAP_HOSTS=openldap # 连接的OpenLDAP服务器
    expose:
      - 80

  redis:
    image: redis
    container_name: ums-redis
    expose:
      - 6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ums-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    expose:
      - 8081

volumes:
  openldap-db:
  openldap-config:
