version: "3.8"

services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    environment:
      - LDAP_ORGANISATION=User Managment System # 组织的名字
      - LDAP_DOMAIN=ums # 公司域名，用于 BASE_DN，不可修改，否则数据库无法启动
      - LDAP_ADMIN_PASSWORD=root # 管理员密码
    volumes:
      - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom # 加载测试数据
      - openldap-db:/var/lib/ldap
      - openldap-config:/etc/ldap/slapd.d
    ports:
      - 389:389
    command: --copy-service

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_HTTPS=false # 关闭HTTPS，开启HTTP。（HTTPS和HTTP只能开启一个）
      - PHPLDAPADMIN_LDAP_HOSTS=openldap # 连接的OpenLDAP服务器
    expose:
      - 80
    ports:
      - 9002:80

  # redis:
  #   image: redis
  #   container_name: redis
  #   ports:
  #     - 6379:6379
  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   container_name: redis-commander
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379
  #   ports:
  #     - 9003:8081

volumes:
  openldap-db:
  openldap-config:
