/**
 * 审批流程 API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5.0
 * Contact: rlee@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.TaskQuery();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TaskQuery', function() {
    it('should create an instance of TaskQuery', function() {
      // uncomment below and update the code to test TaskQuery
      //var instane = new Api.TaskQuery();
      //expect(instance).to.be.a(Api.TaskQuery);
    });

    it('should have the property userId (base name: "userId")', function() {
      // uncomment below and update the code to test the property userId
      //var instane = new Api.TaskQuery();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new Api.TaskQuery();
      //expect(instance).to.be();
    });

    it('should have the property reportNo (base name: "reportNo")', function() {
      // uncomment below and update the code to test the property reportNo
      //var instane = new Api.TaskQuery();
      //expect(instance).to.be();
    });

    it('should have the property plateNo (base name: "plateNo")', function() {
      // uncomment below and update the code to test the property plateNo
      //var instane = new Api.TaskQuery();
      //expect(instance).to.be();
    });

  });

}));
