/**
 * 审批流程 API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5.0
 * Contact: rlee@163.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.ApprovalDetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApprovalDetails', function() {
    it('should create an instance of ApprovalDetails', function() {
      // uncomment below and update the code to test ApprovalDetails
      //var instane = new Api.ApprovalDetails();
      //expect(instance).to.be.a(Api.ApprovalDetails);
    });

    it('should have the property approver (base name: "approver")', function() {
      // uncomment below and update the code to test the property approver
      //var instane = new Api.ApprovalDetails();
      //expect(instance).to.be();
    });

    it('should have the property _date (base name: "date")', function() {
      // uncomment below and update the code to test the property _date
      //var instane = new Api.ApprovalDetails();
      //expect(instance).to.be();
    });

    it('should have the property approved (base name: "approved")', function() {
      // uncomment below and update the code to test the property approved
      //var instane = new Api.ApprovalDetails();
      //expect(instance).to.be();
    });

    it('should have the property comment (base name: "comment")', function() {
      // uncomment below and update the code to test the property comment
      //var instane = new Api.ApprovalDetails();
      //expect(instance).to.be();
    });

  });

}));
