openapi: 3.0.2

info:
  title: 上报审批系统后台服务 API
  version: 0.9.0
  license:
    name: MIT
    url: https://mit-license.org/
  contact:
    name: Ryan Li
    email: rlee@163.com

servers:
  - url: http://localhost:3000/rest
  - url: http://{host}:{port}/{contextPath}
    variables:
      host:
        default: localhost
      port:
        default: "9003"
      contextPath:
        default: rest

paths:
  /application/create:
    post:
      tags:
        - Application
      summary: 创建一个申请
      description: 申请人在“申请页面”填写相关信息并提交申请，将调用此 API 来创建一个新申请。
      operationId: createApplication

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApplicationDetailsDto"
            examples:
              包干修复初审:
                value:
                  state: 初审
                  type: 包干修复
                  applicant: 定损员A
                  startDate: "2020-06-30T14:10:20.391"
                  caseNo: PICC-123456
                  plateNo: 鄂A-12345
                  vehicleModel: 奔驰 GLC 260 豪华型
                  repairPlant: 武汉星隆汽车销售服务有限公司
                  actualCost: "250000"
                  evaluationCost: "250000"
                  purchasePrice: "422800"
                  agreementAmount: "100000"
                  investigator: 定损员A
                  investigateDate: 2020-06-28
              高价值件初审:
                value:
                  state: 初审
                  type: 高价值件
                  applicant: 定损员A
                  startDate: "2020-06-30T14:10:20.391"
                  caseNo: PICC-123456
                  plateNo: 鄂A-12345
                  vehicleModel: 奔驰 GLC 260 豪华型
                  investigator: 定损员A
                  investigateLocation: 武汉星隆汽车销售服务有限公司
                  investigateDate: 2020-06-28
                  identifier: LBVNPU39008SB69093
                  insurer: 市人保营业部
                  insured: 奔驰车主
                  finalAmount: "50000"
                  deductible: "10000"
              总成部件初审:
                value:
                  state: 初审
                  type: 总成部件
                  applicant: 定损员A
                  startDate: "2020-06-30T14:10:20.391"
                  caseNo: PICC-123456
                  plateNo: 鄂A-12345
                  vehicleModel: 奔驰 GLC 260 豪华型
                  investigator: 定损员A
                  investigateLocation: 武汉星隆汽车销售服务有限公司
                  investigateDate: 2020-06-28
                  identifier: LBVNPU39008SB69093
                  insurer: 市人保营业部
                  insured: 奔驰车主
                  finalAmount: "100000"
                  deductible: "20000"
              调价申请初审:
                value:
                  state: 初审
                  type: 包干修复
                  applicant: 定损员A
                  startDate: "2020-06-30T14:10:20.391"
                  caseNo: PICC-123456
                  plateNo: 鄂A-12345
                  vehicleModel: 奔驰 GLC 260 豪华型
                  investigator: 定损员A
                  investigateDate: 2020-06-28
                  occurredDate: 2020-06-14
                  quoteDate: 2020-06-25
                  quoteAmount: "20000"
                  targetAmount: "25000"

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: 返回码。`20000`：成功。
                  data:
                    type: object
                    description: 返回的数据。
                    properties:
                      id:
                        type: string
                        description: 申请id
                example:
                  code: 20000
                  data:
                    id: bc8d2f78-ba94-11ea-b3de-0242ac130004

components:
  schemas:
    ApplicationDetailsDto:
      required:
        - state
        - type
        - applicant
        - startDate
      type: object
      properties:
        state:
          type: string
          description: 审批状态。开始申请时，状态为“初审”。
          enum: [初审, 复审]
        type:
          type: string
          description: 审批类型。
          enum: [包干修复, 高价值件, 总成部件, 调价申请]
        applicant:
          type: string
          description: 申请人用户名（username）。
        startDate:
          type: string
          description: 提交申请的时间，格式为`ISO8601_FORMAT`。
        caseNo:
          type: string
          description: 报案号
        plateNo:
          type: string
          description: 车牌号
        vehicleModel:
          type: string
          description: 车辆型号
        repairPlant:
          type: string
          description: 修理厂名称
        actualCost:
          type: string
          description: 实际价值
        evaluationCost:
          type: string
          description: 评估价值
        purchasePrice:
          type: string
          description: 新车购置价
        agreementAmount:
          type: string
          description: 一次性协议定损金额
        investigator:
          type: string
          description: 定损员真实姓名（name）。
        investigateLocation:
          type: string
          description: 定损地点
        investigateDate:
          type: string
          description: 定损时间
        identifier:
          type: string
          description: 识别代码
        insurer:
          type: string
          description: 承保公司
        insured:
          type: string
          description: 被保险人姓名
        finalAmount:
          type: string
          description: 最终价格
        deductible:
          type: string
          description: 自付标准
        occurredDate:
          type: string
          description: 出险时间
        quoteDate:
          type: string
          description: 报价时间
        quoteAmount:
          type: string
          description: 报价金额
        targetAmount:
          type: string
          description: 目标金额
    # ApprovalDetailsDto:
    #   type: object
    #   properties:
    #     approver:
    #       type: string
    #       description: 审核人
    #     date:
    #       type: string
    #       description: 审核时间
    #     approved:
    #       type: boolean
    #       description: 审核结果。true：通过；false：不通过
    #     comment:
    #       type: string
    #       description: 审核意见
    # ApprovalHistoryDto:
    #   type: object
    #   properties:
    #     approvalHistory:
    #       type: array
    #       description: 审核历史记录，按时间倒序排列。
    #       items:
    #         $ref: "#/components/schemas/ApprovalDetailsDto"
    # TaskQueryDto:
    #   type: object
    #   required:
    #     - userId
    #   properties:
    #     userId:
    #       type: string
    #       description: 用户 id
    #     type:
    #       type: string
    #       description: 申请类型
    #       enum: [包干修复, 高价值件, 总成部件, 调价申请]
    #     caseNo:
    #       type: string
    #       description: 报案号
    #     plateNo:
    #       type: string
    #       description: 车牌号
