version: "3.7"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: approval-api
    environment:
      - 'URLS=[
        {
          name: "上报审批系统 API",
          url: "./approval-system-openapi.yaml"
        }
      ]'
    volumes:
      - ./approval-system-openapi.yaml:/usr/share/nginx/html/approval-system-openapi.yaml
    ports:
      - 81:8080
